export { addListener } from './functions/addListener'
export { addListeners } from './functions/addListeners'
export { appendAllTo } from './functions/appendAllTo'
export { appendTo } from './functions/appendTo'
export { createElement } from './functions/createElement'
export { each } from './common/each'
export { removeListener } from './functions/removeListener'

export { mutator } from './common/mutator'
export { mutate } from './common/mutate'